language: java
script: mvn verify javadoc:javadoc site:site
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk6

before_install:

  - git clone https://github.com/inf295uci-2015/primitive-hamcrest.git  
  - cd primitive-hamcrest  
  - mvn install 
  - cd ../
  - git clone https://github.com/inf295uci-2015/tacoco
  - cd tacoco
  - mvn package
  - cd ../
